name: C Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile C code
      run: gcc -o build Sheep-ProxyChecker/main.c
    - name: Run the program
      run: ./build
