name: C Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Compile C code
      run: gcc -o build main.c

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: build.exe
