name: C Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Compile C code
      run: gcc -o build Sheep-ProxyChecker/main.c
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: Sheep-ProxyChecker/build
